Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -39,8 +39,8 @@ jobs:
           fi
 
           # 使用 grep 提取文件中的 .list 文件下载链接，并追加到 links.txt 中
-          links=$(grep -o 'https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX[^"]*\.list' "$file")
-          
+          links=$(grep -o 'https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX[^"]*\.list' "$file" || echo "grep failed")
+
           # 检查是否找到链接
           if [ -z "$links" ]; then
             echo "No links found in $file"
